### ISSUE TITLE
Blank/black screen in Spotify

### ISSUE THREAD

**Issue by Daksh777** [Daksh777/SpotifyNoPremium#64]
After the new update, Spicetify stopped working with `1.1.83.956.gbe7ea9a7`. To track the progress of the fix of the issue, please see: https://github.com/spicetify/spicetify-cli/issues/1577

It is advised not to upgrade to that version and block the updates or install an older version and block the updates if you updated to the newer version.

**Comment by artemcodes** [comment]
I updated without problems. After the update, the theme got lost, but I ran the commands spicetify `config current_theme SpotifyNoPremium` and `spicetify apply`

OC: windows 10, 
Spotify v. 1.1.83.956.gbe7ea9a7

**Comment by Daksh777** [comment]
I still have the issue, can you tell me your Spicetify version?

**Comment by voedev** [comment]
version 2.9.4

> I still have the issue, can you tell me your Spicetify version?

**Comment by voedev** [comment]
![image](https://user-images.githubusercontent.com/42519520/164545076-5b36aedb-7aef-4902-8722-17be8ab9c765.png)

 Spicetify version 2.9.4

**Comment by Daksh777** [comment]
Fixed in https://github.com/spicetify/spicetify-cli/releases/tag/v2.9.6

**Comment by ValiumBear** [comment]
Still getting blank screen, did clean install multiple times.
